name: CI

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        RESOURCE_GROUP='190800-actions'
        LOCATION='eastus'
        REGISTRY_NAME='acr82ffdb'
        az acr create -g $RESOURCE_GROUP -l $LOCATION --name $REGISTRY_NAME --sku Basic
        az acr login -n $REGISTRY_NAME
        cd golang/
        az acr build -r $REGISTRY_NAME -t hello-golang --file Dockerfile .
        #az container list
