name: CI

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: acr create + build
      env:
        RESOURCE_GROUP: 190800-actions
        LOCATION: eastus
        RANDOM_STR: 82ffdb
      run: |
        cd $GITHUB_WORKSPACE/golang/
        # create container registry
        REGISTRY_NAME="acr${RANDOM_STR}""
        az acr create -g $RESOURCE_GROUP -l $LOCATION --name $REGISTRY_NAME --sku Basic --admin-enabled true
        # build image
        CONTAINER_IMAGE=hello-golang:$(date +%y%m%d)-${{ github.sha }}
        az acr build -r $REGISTRY_NAME -t $CONTAINER_IMAGE --file Dockerfile .
        # create container instance
        REGISTRY_PASSWORD=$(az acr credential show -n $REGISTRY_NAME | jq -r .passwords[0].value)
        az container create --resource-group $RESOURCE_GROUP --location $LOCATION \
            --name aci${RANDOM_STR} \
            --image "${REGISTRY_NAME}.azurecr.io/${CONTAINER_IMAGE}" \
            --registry-login-server "${REGISTRY_NAME}.azurecr.io" \
            --registry-username $REGISTRY_NAME \
            --registry-password $REGISTRY_PASSWORD \
            --cpu 1 \
            --memory 1 \
            --ports 80 \
            --environment-variables LISTEN_PORT=80 \
            --dns-name-label aci${RANDOM_STR}
        az container list
