name: CI

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: acr create + build
      env:
        RESOURCE_GROUP: 190800-actions
        LOCATION: eastus
        REGISTRY_NAME: acr82ffdb
      run: |
        az acr create -g $RESOURCE_GROUP -l $LOCATION --name $REGISTRY_NAME --sku Basic --admin-enabled true
        az acr login -n $REGISTRY_NAME
        cd $GITHUB_WORKSPACE/golang/
        az acr build -r $REGISTRY_NAME -t hello-golang:${{ github.sha }} --file Dockerfile .
        #az container list
